[functions]
directory = "functions/"

[build]
command = """
cd functions/ts-api &&
npm install &&
cd ../.. &&
cargo build --release --bin pokemon-api &&
cp target/release/pokemon-api functions/
"""
publish = "crates"

[[redirects]]
from = "/api/pokemon/:slug"
to = "/.netlify/functions/pokemon-api"
status = 200

[[redirects]]
from = "/api/ts/pokemon/:slug"
to = "/.netlify/functions/ts-api"
status = 200
